export default interface IEcoleFormat {
total_count:number,
results:IResultFormat
}

export interface IResultFormat {
    nom_etablissement:string,
    type_etablissement:string,
    adresse_1:string,
    adresse_3:string,
    code_postal:string,
    code_commune:string,
    nom_commune:string,
    code_departement:string,
    code_region:string,
    telephone:string,
    mail:string,
    nombre_d_eleves:number,
    fiche_onisep:null,
    coordx_origine:string,
    coordy_origine:string,
    latitude:string,
    longitude:string,
    date_ouverture:string,
    date_maj_ligne:string,
    etat:string, 
}

// total_count:number,
// results: [   
// ]







// results:Map [{
//   identifiant_de_l_etablissement:string,
//   nom_etablissement:string,
//   type_etablissement:string,
//   statut_public_prive:string,
//   adresse_1:string,
//   adresse_2:null,
//   adresse_3:string,
//   code_postal:string,
//   code_commune:string,
//   nom_commun:string,
//   code_departement:string,
//   code_academie:string,
//   code_region:string,
//   ecole_maternelle:boolean,
//   ecole_elementaire:boolean,
//   voie_generale:null,
//   voie_technologique:null,
//   voie_professionnelle:null,
//   telephone:string,
//   fax:null,
//   web:null,
//   mail:string,
//   restauration:boolean,
//   hebergement:boolean,
//   ulis:boolean,
//   apprentissage:null,
//   segpa:null,
//   section_arts:null,
//   section_cinema:null,
//   section_theatre:null,
//   section_sport:null,
//   section_internationale:null,
//   section_europeenne:null,
//   lycee_agricole:null,
//   lycee_militaire:null,
//   lycee_des_metiers:null,
//   post_bac:null,
//   appartenance_education_prioritaire:null,
//   greta:null,
//   siren_siret:string,
//   nombre_d_eleves:number,
//   fiche_onisep:null,
//   position:{
//   lon:number,
//   lat:number
//   },
//   type_contrat_prive:string,
//   libelle_departement:string,
//   libelle_academie:string,
//   libelle_region:string,
//   coordx_origine:string,
//   coordy_origine:string,
//   epsg_origine:string,
//   nom_circonscription:string,
//   latitude:string,
//   longitude:string,
//   precision_localisation:string,
//   date_ouverture:string,
//   date_maj_ligne:string,
//   etat:string,
//   ministere_tutelle:string,
//   multi_uai:boolean,
//   rpi_concentre:boolean,
//   rpi_disperse:null,
//   code_nature:number,
//   libelle_nature:string,
//   code_type_contrat_prive:string,
//   pial:string,
//   etablissement_mere:null,
//   type_rattachement_etablissement_mere:null,
//   code_circonscription:string,
//   code_zone_animation_pedagogique:null,
//   libelle_zone_animation_pedagogique:null,
//   code_bassin_formation:string,
//   libelle_bassin_formation:string
//   },
//   {
//       identifiant_de_l_etablissement:string,
//       nom_etablissement:string,
//       type_etablissement:string,
//       statut_public_prive:string,
//       adresse_1:string,
//       adresse_2:null,
//       adresse_3:string,
//       code_postal:string,
//       code_commune:string,
//       nom_commun:string,
//       code_departement:string,
//       code_academie:string,
//       code_region:string,
//       ecole_maternelle:boolean,
//       ecole_elementaire:boolean,
//       voie_generale:null,
//       voie_technologique:null,
//       voie_professionnelle:null,
//       telephone:string,
//       fax:null,
//       web:null,
//       mail:string,
//       restauration:boolean,
//       hebergement:boolean,
//       ulis:boolean,
//       apprentissage:null,
//       segpa:null,
//       section_arts:null,
//       section_cinema:null,
//       section_theatre:null,
//       section_sport:null,
//       section_internationale:null,
//       section_europeenne:null,
//       lycee_agricole:null,
//       lycee_militaire:null,
//       lycee_des_metiers:null,
//       post_bac:null,
//       appartenance_education_prioritaire:null,
//       greta:null,
//       siren_siret:string,
//       nombre_d_eleves:number,
//       fiche_onisep:null,
//       position:{
//       lon:number,
//       lat:number
//       },
//       type_contrat_prive:string,
//       libelle_departement:string,
//       libelle_academie:string,
//       libelle_region:string,
//       coordx_origine:string,
//       coordy_origine:string,
//       epsg_origine:string,
//       nom_circonscription:string,
//       latitude:string,
//       longitude:string,
//       precision_localisation:string,
//       date_ouverture:string,
//       date_maj_ligne:string,
//       etat:string,
//       ministere_tutelle:string,
//       multi_uai:boolean,
//       rpi_concentre:boolean,
//       rpi_disperse:null,
//       code_nature:number,
//       libelle_nature:string,
//       code_type_contrat_prive:string,
//       pial:string,
//       etablissement_mere:null,
//       type_rattachement_etablissement_mere:null,
//       code_circonscription:string,
//       code_zone_animation_pedagogique:null,
//       libelle_zone_animation_pedagogique:null,
//       code_bassin_formation:string,
//       libelle_bassin_formation:string
//       },
//       {
//           identifiant_de_l_etablissement:string,
//           nom_etablissement:string,
//           type_etablissement:string,
//           statut_public_prive:string,
//           adresse_1:string,
//           adresse_2:null,
//           adresse_3:string,
//           code_postal:string,
//           code_commune:string,
//           nom_commun:string,
//           code_departement:string,
//           code_academie:string,
//           code_region:string,
//           ecole_maternelle:boolean,
//           ecole_elementaire:boolean,
//           voie_generale:null,
//           voie_technologique:null,
//           voie_professionnelle:null,
//           telephone:string,
//           fax:null,
//           web:null,
//           mail:string,
//           restauration:boolean,
//           hebergement:boolean,
//           ulis:boolean,
//           apprentissage:null,
//           segpa:null,
//           section_arts:null,
//           section_cinema:null,
//           section_theatre:null,
//           section_sport:null,
//           section_internationale:null,
//           section_europeenne:null,
//           lycee_agricole:null,
//           lycee_militaire:null,
//           lycee_des_metiers:null,
//           post_bac:null,
//           appartenance_education_prioritaire:null,
//           greta:null,
//           siren_siret:string,
//           nombre_d_eleves:number,
//           fiche_onisep:null,
//           position:{
//           lon:number,
//           lat:number
//           },
//           type_contrat_prive:string,
//           libelle_departement:string,
//           libelle_academie:string,
//           libelle_region:string,
//           coordx_origine:string,
//           coordy_origine:string,
//           epsg_origine:string,
//           nom_circonscription:string,
//           latitude:string,
//           longitude:string,
//           precision_localisation:string,
//           date_ouverture:string,
//           date_maj_ligne:string,
//           etat:string,
//           ministere_tutelle:string,
//           multi_uai:boolean,
//           rpi_concentre:boolean,
//           rpi_disperse:null,
//           code_nature:number,
//           libelle_nature:string,
//           code_type_contrat_prive:string,
//           pial:string,
//           etablissement_mere:null,
//           type_rattachement_etablissement_mere:null,
//           code_circonscription:string,
//           code_zone_animation_pedagogique:null,
//           libelle_zone_animation_pedagogique:null,
//           code_bassin_formation:string,
//           libelle_bassin_formation:string
//           }]